event_Schedule/config/routes.rb
Rails.application.routes.draw do

  root 'users#start_page'

  

  get 'sign_up' => 'users#new', as: :sign_up

  get 'log_out' => 'sessions#destroy', as: :log_out

  post 'user/create' => 'users#create', as: :user_create

  get 'start_page' => 'users#new',as: :user_new

  get 'login' => 'sessions#new', as: :login_new

  post 'login/create' => 'sessions#create', as: :session_create

  get 'event/:user_id/new' => 'events#new',as: :event_new

  post 'event/:user_id/create' => 'events#create',as: :event_create

  get 'event/:user_id/list' => 'events#index',as: :event_list

  get 'event/:id/edit' => 'events#edit',as: :event_edit

  put 'event/:id/edit' => 'events#update', as: :event_update

end

event_Schedule/app/models/event.rb
class Event < ActiveRecord::Base
	has_many :invitations
	has_many :invitees,through: :invitations,foreign_key: :invitee_id
	belongs_to :owner,class_name: "User"

end

event_Schedule/app/models/invitation.rb
class Invitation < ActiveRecord::Base
	# belongs_to :invitee,class_name: "User"
	# belongs_to :inviter,class_name: "User"
	belongs_to :event
	belongs_to :invitee,class_name: "User"
end

event_Schedule/app/models/user.rb
class User < ActiveRecord::Base
  has_many :invitations,foreign_key: :invitee_id
  has_many :events,through: :invitations


  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

event_Schedule/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  helper_method :current_user


  private   
     def current_user
         @current_user ||= User.find(session[:user_id]) if session[:user_id]   
    end
end

event_Schedule/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :edit_event, :find_user

	def new
		@users=User.all
		@event=Event.new
		@events=Event.all
		
		# @user=User.new
	end

	def create
		@event=Event.new(event_params)
		# binding.pry
		@event.owner_id=params[:user_id]
		@event.save
		 params[:invitee_ids].each do |t|
            @invitation=Invitation.new
            @invitation.event_id=@event.id
            @invitation.invitee_id=t
            @invitation.inviter_id=params[:user_id]
        @invitation.save
        end
        redirect_to event_list_path

	end

	def index
		@events=Event.all
		@users=User.all
	end

	def edit
		@users=User.all
		@event=Event.find_by_id(params[:id])
		
		# @events=@event_edit
		# @event_edit=@event_edit.id
	end

	def update
		@event=Event.find_by_id(params[:id])
		@event.update_attributes(event_params)
	 	redirect_to event_list_path(@event)
	end

	private
	def event_params
	  params.require(:event).permit(:event_title, :venue,:date,:time,:invitees,:description,:status,:owner_id)
	end

	def edit_event
		@event_edit=Event.find_by_id(params[:id])
	end

	def find_user
		@user=User.find_by_id(params[:user_id])
	end
end

event_Schedule/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

   def create
    user = User.authenticate(params[:email], params[:password])
    if user
    	session[:user_id] = user.id
    	redirect_to event_list_path(user), :notice => "Logged in!"
  	else
   	 	flash.now.alert = "Invalid email or password"
    	render "new"
  	end
   end

   def destroy
   	  session[:user_id] = nil
  	  redirect_to login_new_path, :notice => "Logged out!"
   end
end

event_Schedule/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def start_page
	end

	def new
  		@user = User.new
	end

	def create
		@user = User.new(user_params)
  		if @user.save
    		redirect_to login_new_path, :notice => "Signed up!"
  		else
    		render "new"
  		end
	end

	private

  	def user_params
   	 params.require(:user).permit(:firstname,:lastname,:username,:email,:phonenumber, :password,:password_confirmation)
  	end
end

event_Schedule/app/helpers/application_helper.rb
module ApplicationHelper
end

event_Schedule/app/helpers/events_helper.rb
module EventsHelper
end

event_Schedule/app/helpers/sessions_helper.rb
module SessionsHelper
end

event_Schedule/app/helpers/users_helper.rb
module UsersHelper
end

event_Schedule/app/views/events/edit.html.erb
 <%if current_user.id == @event.owner_id%>

<%= form_for @event,url: event_update_path(@event), method: :put do |f| %>
  
   <p>
    <%= f.label :Event %><br />
    <%= f.text_field :event_title %>
  </p>
   <p>
    <%= f.label :Venue %><br />
    <%= f.text_field :venue %>
  </p>
   <p>
    <%= f.label :Date%><br />
    <%= f.text_field :date %>
  </p>
   <p>
    <%= f.label :Time%><br />
    <%= f.text_field :time %>
  </p>
  
  



   <%= f.label :Invitees %>
 <ul>
   <% @users.each do |role| %>
     <li>
       <%= check_box_tag 'invitee_ids[]', role.id -%>
       <%= role.username -%>
     </li>
   <% end %>
 </ul>
   <p>
    <%= f.label :Description %><br />
    <%= f.text_area :description %>
  </p>


   <p>
    <%= f.label :Status %><br />
    <%= f.select :status, ['open', 'closed']%></br></br></br>
  </p>
  
   
  <p class="button"><%= f.submit :OK %></p>
  <p class="button"><%= f.submit :Cancel %></p>
  
  <% end %>
  <%else%>
  <%= form_for @event,url: event_update_path(@event), method: :put do |f| %>
  
   <p>
    <%= f.label :Event %><br />
    <%= f.text_field :event_title,:disabled => true %>
  </p>
   <p>
    <%= f.label :Venue %><br />
    <%= f.text_field :venue,:disabled => true %>
  </p>
   <p>
    <%= f.label :Date%><br />
    <%= f.text_field :date %>
  </p>
   <p>
    <%= f.label :Time%><br />
    <%= f.text_field :time %>
  </p>
 

   <%= f.label :Invitees %>
 <ul>
   <% @users.each do |role| %>
     <li>
       <%= check_box_tag 'invitee_ids[]', role.id -%>
       <%= role.username -%>
     </li>
   <% end %>
 </ul>
   <p>
    <%= f.label :Description %><br />
    <%= f.text_area :description,:disabled => true %>
  </p>


   <p>
    <%= f.label :Status %><br />
    <%= f.select :status, ['open', 'closed']%></br></br></br>
  </p>
  
   
  <p class="button"><%= f.submit :OK %></p>
  <p class="button"><%= f.submit :Cancel %></p>
  
  <% end %>
  <%end%>

 

 

event_Schedule/app/views/events/index.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="row">
<div class="col-xs-6">
<% @events.each do |event| %>  
  <div class="row" style="background-color:#D3D3D3; margin:5px; padding:20px">
  <label style="color:green">Event:</label><label>
   <%= event.event_title %></label><br>
  <label style="color:green">Organizer:</label><label> 
  <%= var= event.owner_id %><br>
    <% s=User.find_by_id(var) %>  
  </label> <br>
   
<label style="color:green">Description: </label><label><%= event.description %></label> </br>
  <%= link_to 'Edit Event',event_edit_path(event) %>     
   <div class="container">
  <a data-toggle="modal" data-target="#myModal2-<%= event.id %>">Participants</a> 
    <div class="modal fade" id="myModal2-<%= event.id %>" role="dialog">
     <div class="modal-dialog">

  
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal">&times;</button>
       <h4 class="modal-title">List of Participants</h4>
     </div>
     <div class="modal-body">
     <% event.invitees.each do |user| %>
       <p><%= user.firstname %></p>
     <% end %>
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
     </div>
   </div>
 
 </div>
</div></div>    </div>

<% end %>
</div></br></br></br>
<div class="col-xs-6">
 <%= link_to '<button type="button">Create Event </button>'.html_safe, event_new_path(params[:user_id]) %>


</div>
 </div>

event_Schedule/app/views/events/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-3" >

</div>

<div class="col-md-6" >
<div class="form" style="background-color:DarkSeaGreen">
<h1>Create Event</h1>


<%= form_for :event, url: event_create_path do |f| %>
  
   <p>
    <%= f.label :Event %><br />
    <%= f.text_field :event_title %>
  </p>
   <p>
    <%= f.label :Venue %><br />
    <%= f.text_field :venue %>
  </p>
   <p>
    <%= f.label :Date%><br />
    <%= f.text_field :date %>
  </p>
   <p>
    <%= f.label :Time%><br />
    <%= f.text_field :time %>
  </p>
  

 <%= f.label :Invitees %>
 <ul>
   <% @users.each do |role| %>
     <li>
       <%= check_box_tag 'invitee_ids[]', role.id -%>
       <%= role.username -%>
     </li>
   <% end %>
 </ul>

   <p>
    <%= f.label :Description %><br />
    <%= f.text_area :description %>
  </p>
   <p>
    <%= f.label :Status %><br />
    <%= f.select :status, ['open', 'closed']%></br></br></br>
  </p>
  
   
  <p class="button"><%= f.submit :OK %></p>
  <p class="button"><%= f.submit :Cancel %></p>
<% end %>
</div>
</div>
<div class="col-md-3">
</div>
</div>
</div>

event_Schedule/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventSchedule</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-1.3.2.min', 'jquery.validate.min', 'application' %>
  <%= javascript_include_tag 'jquery-1.3.2.min', 'jquery.validate.min', 'application' %>
<%= javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" %>
</head>
<body>
<header>
<!-- <h1>event scheduler</h1> -->
<div class="img1">
 <%= image_tag("logo2.png") %></div>
<div class="left">
<div id="user_nav">
 <% if current_user %>
   Logged in as <%= current_user.username %>.
   <%= link_to '<button type="button">Log Out</button>'.html_safe, log_out_path %>
 <% else %>
  <%= link_to '<button type="button">Sign Up </button>'.html_safe, sign_up_path %>
 <%= link_to '<button type="button">Log In</button>'.html_safe, login_new_path %>
 <% end %>
</div>
</div>
</header>


<%= yield %></br></br></br></br></br></br></br></br></br></br></br></br>


<footer>
 
  <p style="text-align:center;background-color:grey;">@copyrights 2016.All rights reserved</p>
  

</footer>
</div>


</body>
</html>

event_Schedule/app/views/users/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-3"></div>

<div class="col-md-6" >
<div class="form" style="background-color:DarkSeagreen">
<h1>Sign Up</h1>


<%= form_for @user,:html => {:id => "foo"},url: user_create_path do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <p>
    <%= f.label :FirstName %><br />
    <%= f.text_field :firstname %>
  </p>
   <p>
    <%= f.label :LastName %><br />
    <%= f.text_field :lastname %>
  </p>
   <p>
    <%= f.label :Username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>
   <p>
    <%= f.label :PhoneNumber %><br />
    <%= f.text_field :phonenumber %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit :OK %></p>
  <p class="button"><%= f.submit :Cancel %></p>
<% end %>
</div>
</div>
<div class="col-md-3">
</div>
</div>
</div>

event_Schedule/app/views/users/start_page.html.erb
<!-- div class="container">
<div class="row">
<div class="col-md-3">
</div>
<div class="col-md-6"> -->
<div class="img">
   <%= image_tag("event.jpg") %></div>
   <!-- </div>
   <div class="col-md-3">
   </div>
   </div>
   </div>
   </div>
 -->